name: Ma première CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Récupération du dépôt
      - uses: actions/checkout@v3

      # Installation de Node.js 20
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'

      # Installation des dépendances
      - run: npm ci

      # Lint
      - run: npm run lint

      # Tests
      - run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy sur Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}

  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()  # s'exécute même si le build ou deploy échoue
    steps:
      - name: Discord notification
        run: |
          # Détecte le succès ou l'échec du job deploy
          if [ "${{ needs.deploy.result }}" == "success" ]; then
            STATUS="🛠️ Build terminé impeccable"
          else
            STATUS="❌ Pipeline FAILED ! Vérifiez les logs."
          fi

          echo "Envoi de la notification Discord: $STATUS"

          # Envoi via curl
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{"content":"Test ci/cd\nAPP\n'"$STATUS"'\nRepo : '${{ github.repository }}'\nRef : '${{ github.ref_name }}'"}' \
               ${{ secrets.DISCORD_WEBHOOK }}
